[project]
name = "Gardening"
site_name = "Gardening"
repo_url = "https://github.com/nicholaswilde/gardening"
repo_name = "nicholaswilde/gardening"
docs_dir = "docs"
site_url = "https://nicholaswilde.io/gardning"
copyright = "Copyright &copy; 2026 Nicholas Wilde"
dev_addr = "0.0.0.0:8000"
edit_uri = "edit/main/docs/"

[[project.nav]]
"Home" = "index.md"

[[project.nav]]
"Summary Dashboard" = "seasonal-dashboard.md"

[[project.nav]]
Plants = [
  { "Butterfly Bush" = "plants/butterfly-bush.md" },
  { "Boxleaf Euonymus" = "plants/boxleaf-euonymus.md" },
  { "Crape Myrtle" = "plants/crape-myrtle.md" },
  { "Fern Pine" = "plants/fern-pine.md" },
  { "Foxtail Fern" = "plants/foxtail-fern.md" },
  { "Iceburg Rose" = "plants/iceburg-rose.md" },
  { "Indian Hawthorn" = "plants/indian-hawthorn.md" },
  { "Large Wild Iris" = "plants/large-wild-iris.md" },
  { "Janet Craig Master Bedroom" = "plants/dracaena-janet-craig-1.md" },
  { "Janet Craig Bedroom" = "plants/dracaena-janet-craig-2.md" },
  { "Jalapeño Pepper" = "plants/jalapeno-pepper.md" },
  { "Lily Turf" = "plants/lily-turf.md" },
  { "Marathon II Grass" = "plants/marathon-ii-grass.md" },
  { "Mint" = "plants/mint.md" },
  { "Oregano" = "plants/oregano.md" },
  { "Poblano Pepper" = "plants/poblano-pepper.md" },
  { "Rosemary" = "plants/rosemary.md" },
  { "Sungold Tomato" = "plants/sungold-tomato.md" },
  { "Thyme" = "plants/thyme.md" },
  { "Western Redbud" = "plants/western-redbud.md" }
]

[[project.nav]]
Infrastructure = [
  { "Backyard Pot 1" = "containers/backyard-pot-1.md" },
  { "Raised Bed 1" = "beds/raised-bed-1.md" },
  { "Raised Bed 2" = "beds/raised-bed-2.md" },
  { "Raised Bed 3" = "beds/raised-bed-3.md" },
  { "Click & Grow" = "infrastructure/click-and-grow.md" },
  { "Irrigation" = "infrastructure/irrigation.md" }
]

[[project.nav]]
Archive = [
  { "2025" = [
  { "Basil" = "plants/basil-2025.md" },
  { "Chives Common" = "plants/chives-common-2025.md" },
  { "Cilantro" = "plants/cilantro-2025.md" },
  { "Flat Leaf Parsley" = "plants/flat-leaf-parsley-2025.md" },
  { "Sage" = "plants/sage-2025.md" }
  ] },
]

[[project.nav]]
Reference = [
  { "Future" = "reference/future.md" },
  { "Development" = "reference/development.md" },
  { "Style Guide" = "reference/style-guide.md" }
]

[project.theme]
features = [
  "content.action.edit",
  "content.action.view"
]

[project.theme.icon]
logo = "material/watering-can"
repo = "fontawesome/brands/github"
# 
# [project.theme.palette]
# scheme = "sate"
# primary = "custom"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.extra]
social = [
  { icon = "fontawesome/solid/house", link = "https://nicholaswilde.io/" },
  { icon = "fontawesome/brands/github", link = "https://github.com/nicholaswilde" },
  { icon = "fontawesome/brands/twitter", link = "https://twitter.com/nicholascwilde" },
  { icon = "fontawesome/brands/instagram", link = "https://www.instagram.com/wildewoodworking/" },
  { icon = "fontawesome/brands/linkedin-in", link = "https://www.linked.com/in/nicholaswilde" },
  { icon = "fontawesome/brands/facebook", link = "https://www.facebook.com/nicholas.wilde/" },
  { icon = "fontawesome/brands/keybase", link = "https://keybase.io/nicholaswilde" },
  { icon = "fontawesome/solid/key", link = "https://github.com/nicholaswilde.gpg" },
]

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
