[project]
name = "Gardening"
site_name = "Gardening"
repo_url = "https://github.com/nicholaswilde/gardening"
repo_name = "nicholaswilde/gardening"
docs_dir = "docs"
site_url = "https://nicholaswilde.io/gardning"
copyright = "Copyright &copy; 2026 Nicholas Wilde"
dev_addr = "0.0.0.0:8000"
edit_uri = "edit/main/docs/"

[[project.nav]]
"Home" = "index.md"

[[project.nav]]
Plants = [
  { "Jalepeno Pepper" = "plants/jalepeno-pepper.md" },
  { "Oregano" = "plants/oregano.md" },
  { "Pablano Pepper" = "plants/pablano-pepper.md" },
  { "Rosemary" = "plants/rosemary.md" },
  { "Sungold Tomato" = "plants/sungold-tomato.md" },
  { "Thyme" = "plants/thyme.md" }
]

[[project.nav]]
Infrastructure = [
  { "Backyard Pot 1" = "containers/backyard-pot-1.md" },
  { "Raised Bed 1" = "beds/raised-bed-1.md" },
  { "Raised Bed 2" = "beds/raised-bed-2.md" },
  { "Raised Bed 3" = "beds/raised-bed-3.md" },
  { "Click & Grow" = "infrastructure/click-and-grow.md" },
  { "Irrigation" = "infrastructure/irrigation.md" }
]

[[project.nav]]
Archive = [
  { "2025" = [
    { "Chives Common" = "plants/chives-common-2025.md" },
    { "Cilantro" = "plants/cilantro-2025.md" },
    { "Flat Leaf Parsley" = "plants/flat-leaf-parsley-2025.md" },
    { "Sage" = "plants/sage-2025.md" }
  ] },
]

[[project.nav]]
Reference = [
  { "Future" = "reference/future.md" },
  { "Development" = "reference/development.md" }
]

# [project.nav."Infrastructure"]


[project.theme]
features = [
  "content.action.edit",
  "content.action.view"
]

[project.theme.icon]
logo = "material/watering-can"
repo = "fontawesome/brands/github"

[project.theme.palette]
scheme = "sate"
primary = "custom"

[project.extra]
social = [
  { icon = "fontawesome/solid/house", link = "https://nicholaswilde.io/" },
  { icon = "fontawesome/brands/github", link = "https://github.com/nicholaswilde" },
  { icon = "fontawesome/brands/twitter", link = "https://twitter.com/nicholascwilde" },
  { icon = "fontawesome/brands/instagram", link = "https://www.instagram.com/wildewoodworking/" },
  { icon = "fontawesome/brands/linkedin-in", link = "https://www.linked.com/in/nicholaswilde" },
  { icon = "fontawesome/brands/facebook", link = "https://www.facebook.com/nicholas.wilde/" },
  { icon = "fontawesome/brands/keybase", link = "https://keybase.io/nicholaswilde" },
  { icon = "fontawesome/solid/key", link = "https://github.com/nicholaswilde.gpg" },
]

[project.markdown_extensions."pymdownx.superfences"]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "!!python/name:pymdownx.superfences.fence_mermaid_format" }
]

